### ISSUE TITLE
Photos failing to attach correctly in 2.3 officer map

### ISSUE THREAD

**Issue by richardcesdm** [tonypesdm/CAMS#52]
**Page:** Officer map (page6)
**Form:** All (Issue, Furniture, Surface)

**Description:** Photos submitted against records in the officer map (new or existing) do not appear in CAMS Desktop. This is because the recordGUID in the submitted xml that goes into the webHolding table does not match the associatedRecordID value that goes into webHoldingDocuments

**Suggestion:** Please can you ensure the two ID's match. They currently match on other submissions e.g. report a fault / submissions on My Tasks page.

**Example:** 
In the staging DB, webHolding record with holdingID 3313 has a recordGUID of:
3f417e7f-c908-4ed1-963e-9ff06be04d39
The corresponding webholdingdocuments entry (ID 249) has a associatedRecordID of:
23E1EFE6-FA4A-4FC2-AED4-22A862BFBCDE

**Comment by joerichardsESDM** [comment]
problem here was a discrepancy between the new-style submissions and the old.

In the old-style, the new record guid was created by the handler and this guid was used in both the issue submission and the photo upload; therefore the link between the two was maintained.

In the new-style, the guid creation for the issue submission happens in the API whilst the photo upload still used the guid created by the handler. This meant that the photo upload and the issue submission had different guids and therefore the link was broken.

I have amended this so that the handler-created guid is passed to the API on new submissions and no guid is created in the API. This requires a change to the CAMSWeb code & the API (now on v4.6.0.3).

**Comment by richardcesdm** [comment]
tested and all good
